:sparkles: Manage Security Groups using OpenStackClusterTemplate
SovereignCloudStack/cluster-stacks pull request #138
Opened 2024-07-11 12:23 UTC by michal-gubricky

**What this PR does / why we need it**:
This PR adds security rules for the Cilium.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #74 

**Special notes for your reviewer**:
This is how security groups for controlplane and worker nodes looks like:
![sec-group-contorlplane](https://github.com/SovereignCloudStack/cluster-stacks/assets/72123234/184bb23b-538f-41b8-8cec-e5f223e83076)
![sec-groups-worker](https://github.com/SovereignCloudStack/cluster-stacks/assets/72123234/db0f6081-2f9e-40e8-9961-68e3a48693e3)

2024-07-17 08:01 UTC, DEiselt reviewed
Nice work, i am unfortunately unable to test this due to issues with the infrastructure providers i have access to.

2024-07-18 07:59 UTC, DEiselt approved these changes
Was able to test now.

2024-07-19 10:55 UTC, chess-knight requested changes

2024-07-19 10:55 UTC, chess-knight commented on providers/openstack/scs/cluster-class/templates/openstack-cluster-template.yaml
You also want to remove the patch for the `allowAllInClusterTraffic` when the `openstack_security_groups` are used.

2024-07-19 12:30 UTC, michal-gubricky commented on providers/openstack/scs/cluster-class/templates/openstack-cluster-template.yaml
Thanks, I will take a look at it

2024-07-19 12:42 UTC, chess-knight approved these changes
LGTM

2024-07-19 12:47 UTC, merged